import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

//added for auth
import { ClerkProvider } from '@clerk/nextjs'


import { ThemeProvider } from '@/components/theme-provider'

import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //Auth part: wrap the entire application with clerk provider
  //add cn ("bg-secondary") to body so that the whole UI looks better
  return (
    <ClerkProvider> 
      <html lang="en" suppressHydrationWarning>
        <body className={cn("bg-secondary", inter.className)}> 
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
           {children}
          </ThemeProvider>
          </body>
      </html>
    </ClerkProvider>
  )
}


//for mode changing, if you want to stay in one mode
//you can force it
//change here: <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
//to  <ThemeProvider attribute="class" forcedTheme="dark" enableSystem>

